# Generated by Django 5.2 on 2025-11-26 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id_admin",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("nama_admin", models.CharField(max_length=100)),
                ("user_admin", models.CharField(max_length=50)),
                ("pass_admin", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Buku",
            fields=[
                (
                    "id_buku",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("judul_buku", models.CharField(max_length=150)),
                ("tgl_terbit", models.DateField()),
                ("nama_pengarang", models.CharField(max_length=100)),
                ("nama_penerbit", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Peminjam",
            fields=[
                (
                    "id_peminjam",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("nama_peminjam", models.CharField(max_length=100)),
                ("tgl_daftar", models.DateField()),
                ("user_peminjam", models.CharField(max_length=50)),
                ("pass_peminjam", models.CharField(max_length=8)),
                ("foto_peminjam", models.CharField(max_length=255)),
                ("status_peminjam", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Peminjaman",
            fields=[
                (
                    "kode_pinjam",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("tgl_pesan", models.DateField()),
                ("tgl_ambil", models.DateField()),
                ("tgl_wajibkembali", models.DateField()),
                ("tgl_kembali", models.DateField(blank=True, null=True)),
                ("status_pinjam", models.CharField(max_length=15)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="peminjaman_buku.admin",
                    ),
                ),
                (
                    "peminjam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="peminjaman_buku.peminjam",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DetilPeminjaman",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_buku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="peminjaman_buku.buku",
                    ),
                ),
                (
                    "kode_pinjam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="peminjaman_buku.peminjaman",
                    ),
                ),
            ],
            options={
                "unique_together": {("kode_pinjam", "id_buku")},
            },
        ),
    ]
