# Generated by Django 5.2 on 2025-11-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peminjaman_buku", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="pass_admin",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="peminjam",
            name="pass_peminjam",
            field=models.CharField(max_length=128),
        ),
    ]
